bash: misc tidies, extend `trawl`, add `xd`
Signed-off-by: Richard Mortier <mort@cantab.net>

diff --git a/environment b/environment
--- a/environment
+++ b/environment
@@ -1,6 +1,6 @@
 # -*- mode: sh -*-
 #
-# Copyright (C) 2000--2014 Richard Mortier <mort@cantab.net>.  All Rights
+# Copyright (C) 2000--2021 Richard Mortier <mort@cantab.net>.  All Rights
 # Reserved.
 #
 # This program is free software; you can redistribute it and/or modify
@@ -23,10 +23,8 @@
 
 [ -r ~/rc-files/envfns.sh  ] && source ~/rc-files/envfns.sh
 [ -r ~/rc-files/filefns.sh ] && source ~/rc-files/filefns.sh
-[ -r ~/rc-files/hosts.sh   ] && source ~/rc-files/hosts.sh
-
+[ -r ~/rc-files/hosts.sh ] && source ~/rc-files/hosts.sh
 [ -r ~/src/dockerfiles/dockerfns.sh ] && source ~/src/dockerfiles/dockerfns.sh
-
 [ -r ~/src/sh-scripts/numfns.sh ] && source ~/src/sh-scripts/numfns.sh
 
 #
@@ -43,10 +41,10 @@ KERNEL=$(uname -r)
 LHOST=$(uname -n)
 PLATFORM=$(uname -s)
 SHOST=${LHOST%%.*}
-export LHOST SHOST KERNEL CDPATH
+export CDPATH KERNEL LHOST PLATFORM SHOST
 
-MANPAGER="less -FRXi"
 PAGER="less -FRXi"
+MANPAGER="$PAGER"
 export PAGER MANPAGER
 
 LC_ALL="en_GB.UTF-8"
@@ -99,7 +97,7 @@ case $PLATFORM in
     ;;
 
   Darwin )
-    aenv PATH /usr/local/texlive/2019/bin/x86_64-darwin
+    aenv PATH /usr/local/texlive/2021/bin/universal-darwin
     export EDITOR="emacsclient -s /tmp/emacs-$USER/server"
 
     ## homebrew completion
@@ -194,25 +192,7 @@ ps1nogit() {
 # simpler, happier times
 ps1nogit
 
-# pip bash completion start
-_pip_completion()
-{
-  COMPREPLY=( $( COMP_WORDS="${COMP_WORDS[*]}" \
-                           COMP_CWORD=$COMP_CWORD \
-                           PIP_AUTO_COMPLETE=1 $1 ) )
-}
-complete -o default -F _pip_completion pip
-# pip bash completion end
-
-## Go
-export GOPATH=~/go
-aenv PATH ~/go/bin
-
-## GNU coreutils
-# aenv PATH /usr/local/opt/coreutils/libexec/gnubin
-# aenv MANPATH /usr/local/opt/coreutils/libexec/gnuman
-
-## my PATHs mostly win:
+## my PATHs mostly win
 aenv PATH    ~/me/local/bin
 aenv MANPATH ~/me/local/man
 
@@ -225,9 +205,32 @@ export OCAMLRUNPARAM=b
 # direnv
 [ -x "$(which direnv)" ] && { eval "$(direnv hook bash)" ; direnv reload ; }
 
-# awscli completion
-complete -C aws_completer aws
+## ikva
 
 ## DO/K8s
-export KUBECONFIG=~/.kube/kvasir-alpha-kubeconfig.yaml:~/.kube/k8s-kvasir-kubeconfig.yaml
-helm completion bash > /usr/local/etc/bash_completion.d/helm
+alias k=kubectl
+trap 'rm -f "$TMPFILE"' EXIT
+TMPFILE=$(mktemp)
+if [[ $? -gt 0 ]]; then
+  echo "### COULDN'T CREATE TMPFILE"
+else
+  kubectl completion bash >| $TMPFILE && source $TMPFILE && rm $TMPFILE
+  complete -F __start_kubectl k
+fi
+
+## replaced using `kubectl config view --flatten > ~/.kube/config`
+# for k in ~/.kube/*-kubeconfig.yaml ; do
+#   aenv KUBECONFIG $k
+# done
+export IKVA_ROOT=~/ikva/src
+cp $IKVA_ROOT/ikva-tools/ik ~/me/local/bin
+eval $(helm completion bash)
+
+## yq@3
+aenv PATH /usr/local/opt/yq@3/bin
+
+## terraform
+complete -C /usr/local/bin/terraform terraform
+
+## rust / rustup / cargo
+. "$HOME/.cargo/env"
